name: Go build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: true
        default: 'Test'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff -s --exit-code go.sum
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v .
